import { createHash } from 'node:crypto';
import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type Database from 'better-sqlite3';
import { GlobalsStore } from './store/GlobalsStore.js';

/**
 * The files muxpad keeps in its data dir for prompt injection, and the one
 * rule that makes them boring:
 *
 *   agent-instructions.md  GENERATED. Rewritten from source on EVERY boot.
 *   do-mode.md             GENERATED. Same.
 *   agent-notes.md         THE USER'S. Created once if absent, never touched
 *                          again by muxpad.
 *
 * Injection is `generated + notes`, in that order (agent-instructions.ts).
 *
 * WHY THE SPLIT. One file used to be both: muxpad's capability documentation
 * (which must track the code exactly, always) and the user's machine-specific
 * context (which muxpad must never generate or overwrite). Those requirements
 * are opposites, so the file could only serve one of them — it was user-owned,
 * which meant an install that booted once kept its first-ever default forever
 * and every shipped improvement was invisible. The fix used to be a four-way
 * classifier that hashed the file to guess "did the human edit this?". Split
 * in two and the question disappears: the generated half always matches the
 * build by construction, and the user's half is never written.
 *
 * NOTHING HERE MAY THROW. This runs at boot under launchd KeepAlive, where an
 * EACCES on a read-only data dir is a restart loop rather than an error. Every
 * write degrades to "leave it alone".
 */

export const AGENT_NOTES_FILE = 'agent-notes.md';

/** One-shot marker for {@link migrateAgentFileEdits}. */
const KEY_MIGRATED = 'agent_notes_migrated';

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/** Data-dir resolution for the RUNNER process, which has no Config object:
 *  the same rule the harness uses for its agent-logs dir (index.ts). */
export function runnerDataDir(): string {
  return process.env.MUXPAD_DATA_DIR ?? join(homedir(), '.muxpad');
}

export function agentNotesPath(dataDir: string): string {
  return join(dataDir, AGENT_NOTES_FILE);
}

/** Prepended to every generated file. One line, because it is fed to a model
 *  verbatim along with the rest of the file. */
export const GENERATED_BANNER = `<!-- Generated by muxpad — do not edit; this file is rewritten from source on every start. Your own standing notes go in ${AGENT_NOTES_FILE}, which muxpad creates once and never touches. -->`;

export function generatedBody(seed: string): string {
  return `${GENERATED_BANNER}\n\n${seed}`;
}

/** Write a generated file, banner included. Best-effort: an unwritable data
 *  dir leaves the old copy in place rather than failing the boot. */
export function writeGeneratedFile(dataDir: string, name: string, seed: string): void {
  try {
    writeFileSync(join(dataDir, name), generatedBody(seed));
  } catch {
    // Read-only data dir. The stale copy on disk is a far smaller problem
    // than refusing to start.
  }
}

/** Seed for `agent-notes.md`. An HTML comment so a file the user never fills
 *  in contributes nothing an agent will act on. */
export const AGENT_NOTES_SEED = `<!--
Your standing notes for every agent session on this machine, injected after
muxpad's generated agent-instructions.md on every backend.

muxpad creates this file ONCE and never writes to it again, so anything here
survives every upgrade. Machine-specific context belongs here: where your
projects live, house conventions, people, preferences. Empty the file to
inject nothing.
-->
`;

/** Create the user's notes file if it is absent. Never touches an existing
 *  one — not to update it, not to normalise it, not ever. */
export function ensureAgentNotes(dataDir: string): void {
  const path = agentNotesPath(dataDir);
  if (existsSync(path)) return;
  try {
    writeFileSync(path, AGENT_NOTES_SEED, { flag: 'wx' });
  } catch {
    // Unwritable dir, or someone won the race. Either way: not ours to force.
  }
}

/** Read the user's notes at injection time. Missing/empty/unreadable → null,
 *  and the caller injects nothing. Never an error. */
export function readAgentNotes(dataDir: string): string | null {
  try {
    const text = readFileSync(agentNotesPath(dataDir), 'utf8');
    return text.trim() ? text : null;
  } catch {
    return null;
  }
}

// ─── One-shot migration ─────────────────────────────────────────────────────

/** A file that used to be user-owned and is now generated. */
export interface MigratedFile {
  /** Bare file name inside the data dir. */
  name: string;
  /** sha256 of every default muxpad has EVER shipped for this file, the
   *  current one included. A file matching one of these is untouched plumbing
   *  with nothing to rescue. Add the outgoing hash here whenever the seed
   *  changes, for as long as this migration lives. */
  knownDefaults: readonly string[];
  /** True when the rescued content belongs in `agent-notes.md` (injected into
   *  every session). False for content whose meaning depends on where it was
   *  injected — it is only kept as a `.bak` beside it. */
  appendToNotes: boolean;
}

export interface MigrationResult {
  /** Files whose content was rescued (renamed aside, and appended to notes
   *  when `appendToNotes`). Empty on a pristine or already-migrated install. */
  rescued: string[];
  /**
   * False when a file still holds content of the user's that could NOT be
   * moved out of the way. The caller must not run its generated writes in that
   * case — and it is not hypothetical: a read-only data dir blocks the rename
   * (a directory operation) while still permitting an overwrite of an existing
   * writable file, so "the rescue failed, therefore the overwrite will too" is
   * simply untrue. The marker is left unset, so the next boot tries again.
   */
  safe: boolean;
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/** `agent-instructions.md` → `agent-instructions.md.pre-notes-2026-08-30.bak`,
 *  with a counter if that name is taken. Returns null if no free name exists
 *  (never in practice; the loop just refuses to spin forever). */
function backupPath(dataDir: string, name: string): string | null {
  const base = join(dataDir, `${name}.pre-notes-${today()}`);
  for (let i = 0; i < 100; i++) {
    const candidate = i === 0 ? `${base}.bak` : `${base}.${i}.bak`;
    if (!existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Move anything the user added to the now-generated files somewhere muxpad
 * will never overwrite — ONCE, before the first generated write.
 *
 * The order is what makes it lossless: the old file is RENAMED aside first, so
 * its content is already safe before anything else is attempted. Appending to
 * the notes file comes second and can fail without costing anything. If even
 * the rename fails, {@link MigrationResult.safe} tells the caller to generate
 * nothing this boot.
 *
 * Best-effort throughout, and one-shot behind a globals marker so a user who
 * later deletes their notes doesn't get the old file re-imported.
 */
export function migrateAgentFileEdits(deps: {
  db: Database.Database;
  dataDir: string;
  files: readonly MigratedFile[];
}): MigrationResult {
  const result: MigrationResult = { rescued: [], safe: true };
  let globals: GlobalsStore;
  try {
    globals = new GlobalsStore(deps.db);
    if (globals.get(KEY_MIGRATED)) return result;
  } catch {
    // No globals table (a DB this old cannot have the files either). Do
    // nothing rather than risk running unguarded on every boot.
    return result;
  }

  for (const file of deps.files) {
    try {
      rescueOne(deps.dataDir, file, result);
    } catch {
      // Per-file, so one unreadable file can't strand the other.
      result.safe = false;
    }
  }

  // Only remember having run once every file is genuinely out of the way.
  if (result.safe) {
    try {
      globals.set(KEY_MIGRATED, '1');
    } catch {
      // Worst case we look again next boot — harmless: by then the file on
      // disk is the generated default and matches a known hash.
    }
  }
  return result;
}

function rescueOne(dataDir: string, file: MigratedFile, result: MigrationResult): void {
  const path = join(dataDir, file.name);
  if (!existsSync(path)) return; // pristine install
  const content = readFileSync(path, 'utf8');
  // Untouched plumbing (any default muxpad ever shipped, or an emptied file
  // — the old documented opt-out) carries nothing worth keeping.
  if (!content.trim() || file.knownDefaults.includes(sha256(content))) return;

  const bak = backupPath(dataDir, file.name);
  if (!bak) {
    result.safe = false;
    return;
  }
  renameSync(path, bak); // throws → caught above → safe = false
  result.rescued.push(file.name);
  if (!file.appendToNotes) return;

  ensureAgentNotes(dataDir);
  const notes = (() => {
    try {
      return readFileSync(agentNotesPath(dataDir), 'utf8');
    } catch {
      return '';
    }
  })();
  const heading = `## From ${file.name} (${today()})`;
  const preamble = `<!-- muxpad moved this here: ${file.name} is now generated and rewritten on every start, so your edits could not stay in it. Trim anything below that is just a copy of muxpad's own capability docs; keep what is yours. The original file is beside this one as ${bak.slice(dataDir.length + 1)}. -->`;
  try {
    writeFileSync(
      agentNotesPath(dataDir),
      `${notes.replace(/\s*$/, '')}\n\n${preamble}\n\n${heading}\n\n${content.trim()}\n`,
    );
  } catch {
    // The notes file is unwritable. The user's content is already safe in the
    // .bak — nothing is lost, it just isn't injected until they move it back.
  }
}
