import { describe, expect, it } from 'vitest';
import {
  type ChatEvent,
  LAUNCH_ACK_RE,
  REPLY_ACK,
  REPLY_TOOL_NAME,
  blockText,
  isAgentLaunchTool,
  isInterruptMarker,
  needsReplyFallback,
  normalizeTranscriptLine,
  sanitizeAgentStatus,
  subagentLabel,
  taskNotificationToolUseId,
} from './chat-events.js';

const TS = '2026-07-01T10:00:00.000Z';
const MS = Date.parse(TS);

function kinds(evts: ChatEvent[]): string[] {
  return evts.map((e) => e.kind);
}

describe('normalizeTranscriptLine', () => {
  it('normalizes a plain user message', () => {
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'u1',
      timestamp: TS,
      message: { role: 'user', content: 'hello there' },
    });
    expect(out).toEqual([{ kind: 'user', id: 'u1', ts: MS, text: 'hello there' }]);
  });

  it('drops plumbing user text (caveat / slash-command wrappers)', () => {
    for (const content of [
      'Caveat: The messages below were generated by the user while running local commands.',
      '<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>',
      '<command-name>/clear</command-name>',
      '<local-command-stdout></local-command-stdout>',
      '   ',
    ]) {
      expect(normalizeTranscriptLine({ type: 'user', uuid: 'x', message: { content } })).toEqual(
        [],
      );
    }
  });

  it('turns a task-notification into a notice event (summary + status)', () => {
    const content = [
      '<task-notification>',
      '<task-id>abc</task-id>',
      '<tool-use-id>toolu_1</tool-use-id>',
      '<output-file>/tmp/abc.output</output-file>',
      '<status>completed</status>',
      '<summary>Agent "Restyle ChatPane" finished</summary>',
      '</task-notification>',
    ].join('\n');
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'n1',
      timestamp: TS,
      message: { content },
    });
    expect(out).toEqual([
      {
        kind: 'notice',
        id: 'n1',
        ts: MS,
        variant: 'task',
        text: 'Agent "Restyle ChatPane" finished',
        detail: 'completed',
        toolUseId: 'toolu_1',
      },
    ]);
  });

  it('turns a standalone system-reminder into a notice event', () => {
    const content = '<system-reminder>\nThe user named this session "OTEL".\n</system-reminder>';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'n2', message: { content } });
    expect(out).toEqual([
      {
        kind: 'notice',
        id: 'n2',
        ts: null,
        variant: 'reminder',
        text: 'The user named this session "OTEL".',
      },
    ]);
  });

  it('keeps ordinary user text that merely contains a trailing reminder as a bubble', () => {
    const content = 'do the thing\n<system-reminder>context</system-reminder>';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'u4', message: { content } });
    expect(out).toEqual([{ kind: 'user', id: 'u4', ts: null, text: content }]);
  });

  it('keeps user text with a LEADING injected reminder as a bubble (real text follows)', () => {
    // Claude Code prepends context reminders to real user messages — the
    // human's text after the closing tag must not be swallowed into a notice.
    const content = '<system-reminder>injected context</system-reminder>\n\ndo the thing';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'u5', message: { content } });
    expect(out).toEqual([{ kind: 'user', id: 'u5', ts: null, text: content }]);
  });

  it('keeps text sandwiched between two reminder blocks as a bubble', () => {
    const content =
      '<system-reminder>a</system-reminder>\ndo it\n<system-reminder>b</system-reminder>';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'u6', message: { content } });
    expect(out).toEqual([{ kind: 'user', id: 'u6', ts: null, text: content }]);
  });

  it('splits an assistant line into text + tool_use, carrying the model', () => {
    const out = normalizeTranscriptLine({
      type: 'assistant',
      uuid: 'a1',
      timestamp: TS,
      message: {
        role: 'assistant',
        model: 'claude-opus-4-8',
        content: [
          { type: 'text', text: 'let me check' },
          { type: 'tool_use', id: 'tu_1', name: 'Bash', input: { command: 'ls' } },
        ],
      },
    });
    expect(kinds(out)).toEqual(['assistant', 'tool_use']);
    expect(out[0]).toMatchObject({
      kind: 'assistant',
      text: 'let me check',
      model: 'claude-opus-4-8',
      id: 'a1:0',
    });
    expect(out[1]).toMatchObject({
      kind: 'tool_use',
      name: 'Bash',
      toolUseId: 'tu_1',
      input: { command: 'ls' },
      id: 'a1:1',
    });
  });

  it('normalizes a thinking block', () => {
    const out = normalizeTranscriptLine({
      type: 'assistant',
      uuid: 'a2',
      message: {
        role: 'assistant',
        content: [{ type: 'thinking', thinking: 'hmm', signature: 'x' }],
      },
    });
    expect(out).toEqual([{ kind: 'thinking', id: 'a2:0', ts: null, text: 'hmm' }]);
  });

  it('normalizes a tool_result with a structured diff', () => {
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'u2',
      timestamp: TS,
      toolUseResult: {
        filePath: '/x/y.ts',
        structuredPatch: [{ oldStart: 1, oldLines: 0, newStart: 1, newLines: 1, lines: ['+hi'] }],
      },
      message: {
        role: 'user',
        content: [{ type: 'tool_result', tool_use_id: 'tu_1', content: 'done' }],
      },
    });
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      kind: 'tool_result',
      toolUseId: 'tu_1',
      ok: true,
      text: 'done',
      diff: { filePath: '/x/y.ts' },
    });
    expect((out[0] as { diff: { patch: unknown[] } }).diff.patch).toHaveLength(1);
  });

  it('marks an errored tool_result as not ok and flattens array content', () => {
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'u3',
      message: {
        role: 'user',
        content: [
          {
            type: 'tool_result',
            tool_use_id: 'tu_2',
            is_error: true,
            content: [{ type: 'text', text: 'boom' }],
          },
        ],
      },
    });
    expect(out[0]).toMatchObject({
      kind: 'tool_result',
      ok: false,
      text: 'boom',
      toolUseId: 'tu_2',
    });
  });

  it('drops sub-agent sidechain and meta lines', () => {
    expect(
      normalizeTranscriptLine({
        type: 'assistant',
        isSidechain: true,
        message: { content: [{ type: 'text', text: 'x' }] },
      }),
    ).toEqual([]);
    expect(
      normalizeTranscriptLine({ type: 'user', isMeta: true, message: { content: 'x' } }),
    ).toEqual([]);
  });

  it('drops non-conversational line types and malformed input', () => {
    for (const line of [
      { type: 'system', subtype: 'init', session_id: 's' },
      { type: 'file-history-snapshot' },
      { type: 'queue-operation' },
      { type: 'mode' },
      null,
      42,
      'nope',
      {},
    ]) {
      expect(normalizeTranscriptLine(line)).toEqual([]);
    }
  });
});

describe('sanitizeAgentStatus', () => {
  it('accepts a valid frame and strips unknown/malformed model entries', () => {
    const out = sanitizeAgentStatus({
      t: 'status',
      model: 'claude-x',
      context: { pct: 12, tokens: 24000, max: 200000 },
      models: [
        { value: 'a', displayName: 'A', resolvedModel: 'claude-a' },
        { value: 42, displayName: 'bad' },
        'garbage',
      ],
    });
    expect(out).toEqual({
      model: 'claude-x',
      context: { pct: 12, tokens: 24000, max: 200000 },
      models: [{ value: 'a', displayName: 'A', resolvedModel: 'claude-a' }],
    });
  });

  it('requires a model but treats context as optional', () => {
    expect(sanitizeAgentStatus(null)).toBeNull();
    // Model is mandatory; a frame without one is dropped.
    expect(sanitizeAgentStatus({ context: { pct: 1, tokens: 1, max: 2 } })).toBeNull();
    // No context (Codex/Cursor backends) → valid, context simply omitted.
    expect(sanitizeAgentStatus({ model: 'x' })).toEqual({ model: 'x' });
    // Malformed context is dropped, not fatal — the model still surfaces.
    expect(sanitizeAgentStatus({ model: 'x', context: { pct: '12', tokens: 1, max: 2 } })).toEqual({
      model: 'x',
    });
  });

  it('omits models when the array sanitizes to empty', () => {
    const out = sanitizeAgentStatus({
      model: 'x',
      context: { pct: 1, tokens: 2, max: 3 },
      models: ['junk'],
    });
    expect(out).toEqual({ model: 'x', context: { pct: 1, tokens: 2, max: 3 } });
  });
});

describe('subagent lifecycle recognisers', () => {
  // These are SHARED because the runner (which owns the durable roster) and the
  // web chat (which renders it) must agree byte-for-byte. Two hand-kept copies
  // is how a roster starts disagreeing with the list beside it.

  it('recognises launches and reads their description', () => {
    expect(isAgentLaunchTool('Task')).toBe(true);
    expect(isAgentLaunchTool('Agent')).toBe(true);
    expect(isAgentLaunchTool('Bash')).toBe(false);
    expect(subagentLabel({ description: '  audit the pipeline  ' })).toBe('audit the pipeline');
    expect(subagentLabel({})).toBe('');
    expect(subagentLabel(null)).toBe('');
    expect(subagentLabel({ description: 'x'.repeat(200) })).toHaveLength(80);
  });

  it('tells a background LAUNCH ACK apart from a real completion', () => {
    // The load-bearing distinction: reading the ack as a completion is what
    // used to drop every background agent one second after launch.
    expect(LAUNCH_ACK_RE.test('Agent launched successfully. Task ID: abc')).toBe(true);
    expect(LAUNCH_ACK_RE.test('Async agent launched')).toBe(true);
    expect(LAUNCH_ACK_RE.test('Here is what I found: 3 defects')).toBe(false);
  });

  it('flattens tool_result content in either shape', () => {
    expect(blockText('agent launched successfully')).toBe('agent launched successfully');
    expect(
      blockText([{ type: 'text', text: 'a' }, { type: 'image' }, { type: 'text', text: 'b' }]),
    ).toContain('a');
    expect(blockText(null)).toBe('');
  });

  it('extracts the tool-use-id from a background finish notification', () => {
    const notif =
      '<task-notification><status>completed</status>' +
      '<tool-use-id>toolu_42</tool-use-id><summary>Agent "x" finished</summary>' +
      '</task-notification>';
    expect(taskNotificationToolUseId(notif)).toBe('toolu_42');
    // A notification from a harness predating the field yields null (the
    // description-matched fallback in the client handles those).
    expect(
      taskNotificationToolUseId('<task-notification><summary>done</summary></task-notification>'),
    ).toBeNull();
    expect(taskNotificationToolUseId('just some prose')).toBeNull();
  });
});

// ── Chat mode's voice ───────────────────────────────────────────────────────
// The `reply` tool is the agent's only user-facing channel in Chat mode. It
// reaches every reader of a transcript through THIS function, which is why the
// promotion happens here and not at render time: the archive indexes assistant
// text and not tool_use rows, so a reply normalized as a tool call would be
// invisible to search — the one thing a user is most likely to look for later.

describe('the reply tool in a transcript', () => {
  const assistantLine = (content: unknown[]) => ({
    type: 'assistant',
    uuid: 'u1',
    timestamp: TS,
    message: { model: 'claude-opus-4-8', content },
  });

  it('normalizes a reply call to assistant TEXT, marked as spoken', () => {
    expect(
      normalizeTranscriptLine(
        assistantLine([
          { type: 'tool_use', id: 't1', name: REPLY_TOOL_NAME, input: { text: 'Filed it.' } },
        ]),
      ),
    ).toEqual([
      {
        kind: 'assistant',
        id: 'u1:0',
        ts: MS,
        text: 'Filed it.',
        voice: 'reply',
        model: 'claude-opus-4-8',
      },
    ]);
  });

  it('keeps several replies as several messages, each with its own id', () => {
    const out = normalizeTranscriptLine(
      assistantLine([
        { type: 'tool_use', id: 't1', name: REPLY_TOOL_NAME, input: { text: 'one' } },
        { type: 'tool_use', id: 't2', name: REPLY_TOOL_NAME, input: { text: 'two' } },
      ]),
    );
    expect(out.map((e) => e.id)).toEqual(['u1:0', 'u1:1']);
  });

  it('drops an empty reply rather than rendering a blank bubble', () => {
    expect(
      normalizeTranscriptLine(
        assistantLine([
          { type: 'tool_use', id: 't1', name: REPLY_TOOL_NAME, input: { text: '  ' } },
        ]),
      ),
    ).toEqual([]);
  });

  it('leaves every OTHER tool call a tool call', () => {
    // Matched on the exact SDK-prefixed name — a user's own MCP server
    // exposing a `reply` tool must never be promoted into muxpad's bubbles.
    expect(
      kinds(
        normalizeTranscriptLine(
          assistantLine([
            { type: 'tool_use', id: 't1', name: 'Bash', input: { command: 'ls' } },
            { type: 'tool_use', id: 't2', name: 'mcp__other__reply', input: { text: 'hi' } },
          ]),
        ),
      ),
    ).toEqual(['tool_use', 'tool_use']);
  });

  it("drops the reply's ack — the tool_use is a message, so nothing pairs with it", () => {
    expect(
      normalizeTranscriptLine({
        type: 'user',
        uuid: 'u2',
        timestamp: TS,
        message: {
          role: 'user',
          content: [
            {
              type: 'tool_result',
              tool_use_id: 't1',
              content: [{ type: 'text', text: REPLY_ACK }],
            },
          ],
        },
      }),
    ).toEqual([]);
  });

  it('keeps ordinary tool_results, including ones that merely mention delivery', () => {
    expect(
      kinds(
        normalizeTranscriptLine({
          type: 'user',
          uuid: 'u3',
          timestamp: TS,
          message: {
            role: 'user',
            content: [
              {
                type: 'tool_result',
                tool_use_id: 't9',
                content: [{ type: 'text', text: 'Delivered to the user. [muxpad-reply] and more' }],
              },
            ],
          },
        }),
      ),
    ).toEqual(['tool_result']);
  });
});

describe('the interrupt marker — a Stop, as the transcript records it', () => {
  it('recognises both harness spellings, and nothing else', () => {
    expect(isInterruptMarker('[Request interrupted by user]')).toBe(true);
    expect(isInterruptMarker('[Request interrupted by user for tool use]')).toBe(true);
    expect(isInterruptMarker('  [Request interrupted by user]')).toBe(true);
    expect(isInterruptMarker('the [Request interrupted by user] line')).toBe(false);
    expect(isInterruptMarker('Request interrupted')).toBe(false);
  });

  it('turns a BARE-STRING interrupt into a stopped notice', () => {
    expect(
      normalizeTranscriptLine({
        type: 'user',
        uuid: 'u1',
        timestamp: TS,
        message: { role: 'user', content: '[Request interrupted by user]' },
      }),
    ).toEqual([{ kind: 'notice', id: 'u1', ts: MS, variant: 'interrupted', text: 'Stopped' }]);
  });

  it('turns a BLOCK-ARRAY interrupt into a stopped notice', () => {
    // The shape a Stop lands in when it interrupts a tool call — live-verified.
    // This branch used to read tool_result blocks ONLY, so the marker was
    // dropped whole and a reloaded chat had no idea the turn was stopped.
    expect(
      normalizeTranscriptLine({
        type: 'user',
        uuid: 'u1',
        timestamp: TS,
        message: {
          role: 'user',
          content: [{ type: 'text', text: '[Request interrupted by user for tool use]' }],
        },
      }),
    ).toEqual([{ kind: 'notice', id: 'u1:0', ts: MS, variant: 'interrupted', text: 'Stopped' }]);
  });

  it('leaves an ordinary user message alone', () => {
    expect(
      kinds(
        normalizeTranscriptLine({
          type: 'user',
          uuid: 'u1',
          timestamp: TS,
          message: { role: 'user', content: 'stop asking me that' },
        }),
      ),
    ).toEqual(['user']);
  });
});

describe('needsReplyFallback — the guard, as one rule', () => {
  const turn = (over: Partial<Parameters<typeof needsReplyFallback>[0]> = {}) =>
    needsReplyFallback({ mode: 'chat', humanInitiated: true, replies: 0, ...over });

  it('fires for a silent turn a human was waiting on', () => {
    expect(turn()).toBe(true);
  });

  it('does not fire when the agent actually spoke', () => {
    expect(turn({ replies: 1 })).toBe(false);
  });

  it('does not fire in Agent mode — plain text is the voice there', () => {
    expect(turn({ mode: 'agent' })).toBe(false);
  });

  it('does not fire for a self-initiated wake — nobody is waiting', () => {
    expect(turn({ humanInitiated: false })).toBe(false);
  });

  it('does not fire for a turn the user stopped, or one that failed', () => {
    expect(turn({ interrupted: true })).toBe(false);
    expect(turn({ failed: true })).toBe(false);
  });
});
