import { describe, expect, it } from 'vitest';
import { type ChatEvent, normalizeTranscriptLine, sanitizeAgentStatus } from './chat-events.js';

const TS = '2026-07-01T10:00:00.000Z';
const MS = Date.parse(TS);

function kinds(evts: ChatEvent[]): string[] {
  return evts.map((e) => e.kind);
}

describe('normalizeTranscriptLine', () => {
  it('normalizes a plain user message', () => {
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'u1',
      timestamp: TS,
      message: { role: 'user', content: 'hello there' },
    });
    expect(out).toEqual([{ kind: 'user', id: 'u1', ts: MS, text: 'hello there' }]);
  });

  it('drops plumbing user text (caveat / slash-command wrappers)', () => {
    for (const content of [
      'Caveat: The messages below were generated by the user while running local commands.',
      '<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>',
      '<command-name>/clear</command-name>',
      '<local-command-stdout></local-command-stdout>',
      '   ',
    ]) {
      expect(normalizeTranscriptLine({ type: 'user', uuid: 'x', message: { content } })).toEqual(
        [],
      );
    }
  });

  it('turns a task-notification into a notice event (summary + status)', () => {
    const content = [
      '<task-notification>',
      '<task-id>abc</task-id>',
      '<tool-use-id>toolu_1</tool-use-id>',
      '<output-file>/tmp/abc.output</output-file>',
      '<status>completed</status>',
      '<summary>Agent "Restyle ChatPane" finished</summary>',
      '</task-notification>',
    ].join('\n');
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'n1',
      timestamp: TS,
      message: { content },
    });
    expect(out).toEqual([
      {
        kind: 'notice',
        id: 'n1',
        ts: MS,
        variant: 'task',
        text: 'Agent "Restyle ChatPane" finished',
        detail: 'completed',
      },
    ]);
  });

  it('turns a standalone system-reminder into a notice event', () => {
    const content = '<system-reminder>\nThe user named this session "OTEL".\n</system-reminder>';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'n2', message: { content } });
    expect(out).toEqual([
      {
        kind: 'notice',
        id: 'n2',
        ts: null,
        variant: 'reminder',
        text: 'The user named this session "OTEL".',
      },
    ]);
  });

  it('keeps ordinary user text that merely contains a trailing reminder as a bubble', () => {
    const content = 'do the thing\n<system-reminder>context</system-reminder>';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'u4', message: { content } });
    expect(out).toEqual([{ kind: 'user', id: 'u4', ts: null, text: content }]);
  });

  it('keeps user text with a LEADING injected reminder as a bubble (real text follows)', () => {
    // Claude Code prepends context reminders to real user messages — the
    // human's text after the closing tag must not be swallowed into a notice.
    const content = '<system-reminder>injected context</system-reminder>\n\ndo the thing';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'u5', message: { content } });
    expect(out).toEqual([{ kind: 'user', id: 'u5', ts: null, text: content }]);
  });

  it('keeps text sandwiched between two reminder blocks as a bubble', () => {
    const content =
      '<system-reminder>a</system-reminder>\ndo it\n<system-reminder>b</system-reminder>';
    const out = normalizeTranscriptLine({ type: 'user', uuid: 'u6', message: { content } });
    expect(out).toEqual([{ kind: 'user', id: 'u6', ts: null, text: content }]);
  });

  it('splits an assistant line into text + tool_use, carrying the model', () => {
    const out = normalizeTranscriptLine({
      type: 'assistant',
      uuid: 'a1',
      timestamp: TS,
      message: {
        role: 'assistant',
        model: 'claude-opus-4-8',
        content: [
          { type: 'text', text: 'let me check' },
          { type: 'tool_use', id: 'tu_1', name: 'Bash', input: { command: 'ls' } },
        ],
      },
    });
    expect(kinds(out)).toEqual(['assistant', 'tool_use']);
    expect(out[0]).toMatchObject({
      kind: 'assistant',
      text: 'let me check',
      model: 'claude-opus-4-8',
      id: 'a1:0',
    });
    expect(out[1]).toMatchObject({
      kind: 'tool_use',
      name: 'Bash',
      toolUseId: 'tu_1',
      input: { command: 'ls' },
      id: 'a1:1',
    });
  });

  it('normalizes a thinking block', () => {
    const out = normalizeTranscriptLine({
      type: 'assistant',
      uuid: 'a2',
      message: {
        role: 'assistant',
        content: [{ type: 'thinking', thinking: 'hmm', signature: 'x' }],
      },
    });
    expect(out).toEqual([{ kind: 'thinking', id: 'a2:0', ts: null, text: 'hmm' }]);
  });

  it('normalizes a tool_result with a structured diff', () => {
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'u2',
      timestamp: TS,
      toolUseResult: {
        filePath: '/x/y.ts',
        structuredPatch: [{ oldStart: 1, oldLines: 0, newStart: 1, newLines: 1, lines: ['+hi'] }],
      },
      message: {
        role: 'user',
        content: [{ type: 'tool_result', tool_use_id: 'tu_1', content: 'done' }],
      },
    });
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      kind: 'tool_result',
      toolUseId: 'tu_1',
      ok: true,
      text: 'done',
      diff: { filePath: '/x/y.ts' },
    });
    expect((out[0] as { diff: { patch: unknown[] } }).diff.patch).toHaveLength(1);
  });

  it('marks an errored tool_result as not ok and flattens array content', () => {
    const out = normalizeTranscriptLine({
      type: 'user',
      uuid: 'u3',
      message: {
        role: 'user',
        content: [
          {
            type: 'tool_result',
            tool_use_id: 'tu_2',
            is_error: true,
            content: [{ type: 'text', text: 'boom' }],
          },
        ],
      },
    });
    expect(out[0]).toMatchObject({
      kind: 'tool_result',
      ok: false,
      text: 'boom',
      toolUseId: 'tu_2',
    });
  });

  it('drops sub-agent sidechain and meta lines', () => {
    expect(
      normalizeTranscriptLine({
        type: 'assistant',
        isSidechain: true,
        message: { content: [{ type: 'text', text: 'x' }] },
      }),
    ).toEqual([]);
    expect(
      normalizeTranscriptLine({ type: 'user', isMeta: true, message: { content: 'x' } }),
    ).toEqual([]);
  });

  it('drops non-conversational line types and malformed input', () => {
    for (const line of [
      { type: 'system', subtype: 'init', session_id: 's' },
      { type: 'file-history-snapshot' },
      { type: 'queue-operation' },
      { type: 'mode' },
      null,
      42,
      'nope',
      {},
    ]) {
      expect(normalizeTranscriptLine(line)).toEqual([]);
    }
  });
});

describe('sanitizeAgentStatus', () => {
  it('accepts a valid frame and strips unknown/malformed model entries', () => {
    const out = sanitizeAgentStatus({
      t: 'status',
      model: 'claude-x',
      context: { pct: 12, tokens: 24000, max: 200000 },
      models: [
        { value: 'a', displayName: 'A', resolvedModel: 'claude-a' },
        { value: 42, displayName: 'bad' },
        'garbage',
      ],
    });
    expect(out).toEqual({
      model: 'claude-x',
      context: { pct: 12, tokens: 24000, max: 200000 },
      models: [{ value: 'a', displayName: 'A', resolvedModel: 'claude-a' }],
    });
  });

  it('rejects frames missing model or context fields', () => {
    expect(sanitizeAgentStatus(null)).toBeNull();
    expect(sanitizeAgentStatus({ model: 'x' })).toBeNull();
    expect(
      sanitizeAgentStatus({ model: 'x', context: { pct: '12', tokens: 1, max: 2 } }),
    ).toBeNull();
    expect(sanitizeAgentStatus({ context: { pct: 1, tokens: 1, max: 2 } })).toBeNull();
  });

  it('omits models when the array sanitizes to empty', () => {
    const out = sanitizeAgentStatus({
      model: 'x',
      context: { pct: 1, tokens: 2, max: 3 },
      models: ['junk'],
    });
    expect(out).toEqual({ model: 'x', context: { pct: 1, tokens: 2, max: 3 } });
  });
});
